language: node_js
node_js:
  - "8"
  - "7"
  - "6"
# before_install: yarn global add greenkeeper-lockfile@1
before_script:
  - yarn install
  - greenkeeper-lockfile-update
script: yarn run build
after_script: greenkeeper-lockfile-upload

# notifications:
#   email:
#     - john.doe@example.com
